### ISSUE TITLE
Namespace-level role assignments are created on resource group level

### ISSUE THREAD

**Issue by joachimnielandt** [mspnp/aks-baseline#408]
Hello all,

I am currently experiencing a peculiar problem, where the namespace role assignments (https://github.com/mspnp/aks-baseline/blob/51cd9d0d6065820fd641569ec92ac44dc8c45622/cluster-stamp.bicep#L1956) are not created on the namespace level, but instead on the resource group level. This has the result that the first time, my deployment works fine. The second time I deploy though, I get a deployment error saying the role assignment resource already exists (or cannot be updated).

Below is my adaptation of this repository, in a minimal working example, which results in the described behaviour. Is this something that other users of `aks-baseline` experience? Can I troubleshoot this somehow?

```yaml
targetScope = 'resourceGroup'

var clusterReaderGroupObjectId = 'aaaaa-bbbbb-cccccc-ddddddd-eeeee'

resource clusterReaderRole 'Microsoft.Authorization/roleDefinitions@2018-01-01-preview' existing = {
  name: '7f6c6a51-bcf8-42ba-9220-52d62157d7db'
  scope: subscription()
}

resource aks 'Microsoft.ContainerService/managedClusters@2023-04-01' existing = {
  name: 'my-cluster'
}

#disable-next-line BCP081 // this namespaces child type doesn't have a defined bicep type yet.
resource nsDev 'Microsoft.ContainerService/managedClusters/namespaces@2023-04-01' existing = {
  parent: aks
  name: 'dev'
}

resource maAadEnvReaderGroupClusterReaderRole_roleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: nsDev
  name: guid('aad-dev-reader-group', aks.id, clusterReaderGroupObjectId)
  properties: {
    roleDefinitionId: clusterReaderRole.id
    description: 'Members of this group are readers of the dev namespace in this cluster.'
    principalId: clusterReaderGroupObjectId
    principalType: 'Group'
  }
}
```
